# Generated by Django 4.2.3 on 2024-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_list", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
            ],
        ),
    ]
